openapi: 3.0.0
info:
  description: |
    Pinterest CM sv-cl API
  version: 1.1.0
  title: Pinterbest
  license:
    name: Pinterbest
    url: https://github.com/frontend-park-mail-ru/2021_1_Code_Magicians
servers:
  - url: 'http://52.59.228.167:8081'
    description: Main production server
tags:
  - name: auth
    description: Authorization operations
  - name: pin
    description: Everything about pins
  - name: board
    description: Everything about boards
  - name: profile
    description: Operations about profile
  - name: comments
    description: Operations about comments
paths:
  /auth/signup:
    $ref: paths/auth@signup.yaml
  /auth/login:
    $ref: paths/auth@login.yaml
  /auth/logout:
    $ref: paths/auth@logout.yaml
  /auth/check:
    $ref: paths/auth@check.yaml
  /profile:
    $ref: paths/profile.yaml
  '/profile/{ID_or_username}':
    $ref: 'paths/profile@{ID_or_username}.yaml'
  /profile/password:
    $ref: paths/profile@password.yaml
  /profile/edit:
    $ref: paths/profile@edit.yaml
  /profile/avatar:
    $ref: paths/profile@avatar.yaml
  /profile/delete:
    $ref: paths/profile@delete.yaml
  '/follow/{ID_or_username}':
    $ref: 'paths/follow@{ID_or_username}.yaml'
  /board:
    $ref: paths/board.yaml
  '/board/{boardID}':
    $ref: 'paths/board@{boardID}.yaml'
  '/boards/{authorID}':
    $ref: 'paths/boards@{authorID}.yaml'
  /pin:
    $ref: paths/pin.yaml
  '/pin/{pinID}':
    $ref: 'paths/pin@{pinID}.yaml'
  '/pins/{boardID}':
    $ref: 'paths/pins@{boardID}.yaml'
  '/comment/{pinID}':
    $ref: 'paths/comment@{pinID}.yaml'
  '/comments/{pinID}':
    $ref: 'paths/comments@{pinID}.yaml'
  '/notifications/read/{notificationID}':
    $ref: 'paths/notifications@read@{notificationID}.yaml'
